### ISSUE TITLE
Getting Error: Metadata file not found. Did you include "metadata.json"

### ISSUE THREAD

**Issue by wighawag** [ethereum/source-verify#6]
I upload just one file called metadata.json (is the name important though ?)

The same one mentioned in https://github.com/ethereum/source-verify/issues/5

And I get the following error :

```
Error: Metadata file not found. Did you include "metadata.json"
```

**Comment by chriseth** [comment]
All file names are ignored. The procedure searches all uploaded files for a file that is correct json and searches for a `"language": "Solidity"` part in there. Maybe the upload did not work?

**Comment by wighawag** [comment]
I am using the web interface and it always fails

**Comment by ligi** [comment]
@wighawag do you still face this error?

**Comment by wighawag** [comment]
Yes still same issue 
```
Metadata file not found. Did you include "metadata.json"?
```

My metadata file has the code inlined
I convert the metadata here : https://github.com/pixowl/sandbox-smart-contracts/blob/master/deployments/1/Sand.json
 in a file and upload the file

The address on mainnet : 0x3845badAde8e6dFF049820680d1F14bD3903a5d0

**Comment by wighawag** [comment]
I attempted to fix the issue a while back with https://github.com/ethereum/source-verify/pull/9

But I guess it does not work  (could not test it back then)

**Comment by edisinovcic** [comment]
This definitelly is a bug. I'm adding logs from server:

```
File name invalid!
File data invalid!
File size invalid!
File encoding invalid!
File tempFilePath invalid!
File truncated invalid!
File mimetype invalid!
File md5 invalid!
File mv invalid!
Error: Error: Metadata file not found. Did you include "metadata.json"?
```

@cgewecke could you take a look at this and possibly fix it with better error handling?

**Comment by cgewecke** [comment]
@wighawag @edisinovcic 

Yes, will take a look. Seems like this is happening when the user only submits a single file...

**Comment by edisinovcic** [comment]
@cgewecke That's correct.

**Comment by cgewecke** [comment]
@wighawag 

This is fixed on the staging (unstable) version of the service. Thanks for finding this bug :)

The Sand contracts are [saved in the repository here][1]:

[1]: https://contractrepostaging.komputing.org/contract/mainnet/0x3845badAde8e6dFF049820680d1F14bD3903a5d0/

**Comment by wighawag** [comment]
Just tried staging (https://verificationstaging.komputing.org/) with another contract : https://github.com/pixowl/sandbox-smart-contracts/blob/master/deployments/1/Asset.json
mainnet address: 0x067a1Eb5E383eD24b66D72aAf80d8D7dB3d299A8

And I get the same error : 

```
Metadata file not found. Did you include "metadata.json"?
```

**Comment by edisinovcic** [comment]
@wighawag bug is still existing, will let you know when we fix it. 
cc @cgewecke

**Comment by cgewecke** [comment]
@wighawag @edisinovcic 

Was just able to submit without any problem - can you advise about how to reproduce the bug? 

The second project is at [contractrepostaging here][1]

The metadata file I used only contained the string from [this line at sandbox-smart-contracts][2]

[2]: https://github.com/pixowl/sandbox-smart-contracts/blob/de777da0a4d8f4fd3e5ed6bdd458584aab2a4e26/deployments/1/Asset.json#L1403

[1]: https://contractrepostaging.komputing.org/contract/mainnet/0x067a1Eb5E383eD24b66D72aAf80d8D7dB3d299A8/

My submission screen looked liked this: 

![Screen Shot 2020-03-27 at 8 22 47 AM](https://user-images.githubusercontent.com/7332026/77772060-c4abe080-7004-11ea-9b1f-ad81856b2de9.png)

**Comment by wighawag** [comment]
weird I get that : 

![source-verify](https://user-images.githubusercontent.com/790580/77773485-94366780-7041-11ea-9561-24d6d7668d4a.png)

**Comment by wighawag** [comment]
They have different size. Maybe I miscopied

**Comment by cgewecke** [comment]
@wighawag Ah! Ok that makes sense - thanks.

**Comment by edisinovcic** [comment]
This is fixed with https://github.com/ethereum/source-verify/pull/115

**Comment by saineshnakra** [comment]
Hello, I am making this request 

"    url = "https://sourcify.dev/server/verify"

    m = MultipartEncoder(
        fields={
            'address': contract_address,
            'chain': network,
            'files': ('metadata.json', open(metadata_file, 'rb'), 'application/json'),
            'files': ('TheDAO.sol', open(source_files[0], 'rb'), 'application/octet-stream')
        }
    )

    headers = {
        'Content-Type': m.content_type
    }

"

also tried using multiple ways to do it, it gives this error "Verification failed: 400, {"error":"Metadata file not found. Did you include \"metadata.json\"?","message":"Metadata file not found. Did you include \"metadata.json\"?"}
"
I think I used the way mentioned in the documentations, was I wrong or is it a bug?
